jenkins:
    build: '.'
    volumes:
     - jenkins_home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - 8080:8080
     - 50000:50000
    expose:
     - 3000
     - 8080
# volumes:
#   jenkins_home:
